spring.application.name=demo-websocket-springboot

server.port=8080

# Dev / testing : Load environment variables to use them
spring.config.import=optional:file:.env[.properties]

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# (Optional) For better format about SQL displaying
spring.jpa.properties.hibernate.format_sql=true

# Hibernate & JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true


# Spring Security
security.jwt.secret-key=${SECRET_KEY}
security.jwt.expiration-time=3600000

