spring.application.name=demo-websocket-springboot

server.port=8080

# Spring Boot can infer this from the URL
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# (Optional) For better format about SQL displaying
spring.jpa.properties.hibernate.format_sql=true

# Hibernate & JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Spring Security
security.jwt.secret-key=ZNoCrE7PkyJXosDbGq4FdJcuUPE+n5uFYoqIcaam35EqVOwZXe9oV4JOXA7B8+7LRn3IJ2OWEEMeMEdVAgRpBA==
security.jwt.expiration-time=3600000
